// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDChHqvIAsKkNno41hAijwldnYaCQbgBY0',
    appId: '1:1015355975549:web:17df0df21e613d447d8e14',
    messagingSenderId: '1015355975549',
    projectId: 'final-43e89',
    authDomain: 'final-43e89.firebaseapp.com',
    storageBucket: 'final-43e89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6_j9jw9M_LPRZx-2j1cpw951pQBceAk4',
    appId: '1:1015355975549:android:a4c6fbcc87a649d17d8e14',
    messagingSenderId: '1015355975549',
    projectId: 'final-43e89',
    storageBucket: 'final-43e89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa06kd2iJF7J2WU6QTRo_s2ZpLzwfWCyA',
    appId: '1:1015355975549:ios:fb1fe1326e96db067d8e14',
    messagingSenderId: '1015355975549',
    projectId: 'final-43e89',
    storageBucket: 'final-43e89.appspot.com',
    iosBundleId: 'com.example.veg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa06kd2iJF7J2WU6QTRo_s2ZpLzwfWCyA',
    appId: '1:1015355975549:ios:fb1fe1326e96db067d8e14',
    messagingSenderId: '1015355975549',
    projectId: 'final-43e89',
    storageBucket: 'final-43e89.appspot.com',
    iosBundleId: 'com.example.veg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDChHqvIAsKkNno41hAijwldnYaCQbgBY0',
    appId: '1:1015355975549:web:b3f8dcd7ae870c817d8e14',
    messagingSenderId: '1015355975549',
    projectId: 'final-43e89',
    authDomain: 'final-43e89.firebaseapp.com',
    storageBucket: 'final-43e89.appspot.com',
  );
}
